# Generated by Django 4.1.6 on 2023-03-01 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fruits',
            name='about',
            field=models.CharField(max_length=500),
        ),
    ]
