# Generated by Django 4.1.6 on 2023-03-04 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_fruits_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='fruits',
            name='link',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
    ]
