# Generated by Django 4.1.6 on 2023-03-04 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_fruits_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fruits',
            name='link',
        ),
    ]
